# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: damachad <damachad@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/04/17 10:57:36 by damachad          #+#    #+#              #
#    Updated: 2023/07/11 15:39:00 by damachad         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC = cc
CFLAGS = -Wall -Werror -Wextra
AR = ar -rcs
RM = rm -rf
NAME = libft.a
SRC_LIBFT = ft_atoi.c ft_bzero.c ft_calloc.c ft_isalnum.c ft_isalpha.c ft_isascii.c \
      ft_isdigit.c ft_isprint.c ft_itoa.c ft_memchr.c ft_memcmp.c ft_memcpy.c \
      ft_memmove.c ft_memset.c ft_putchar_fd.c ft_putendl_fd.c ft_putnbr_fd.c \
      ft_putstr_fd.c ft_strchr.c ft_strdup.c ft_strjoin.c ft_striteri.c \
      ft_strlcat.c ft_strlcpy.c ft_strlen.c ft_strncmp.c ft_strnstr.c \
      ft_strrchr.c ft_strtrim.c ft_substr.c ft_tolower.c ft_toupper.c \
      ft_strmapi.c ft_split.c  ft_lstnew.c ft_lstadd_front.c \
	    ft_lstsize.c ft_lstlast.c ft_lstadd_back.c ft_lstdelone.c ft_lstiter.c \
	    ft_lstclear.c ft_lstmap.c
SRC_PRINTF = ft_convert.c ft_printf.c ft_put_add.c \
			ft_putchar_2.c ft_putnbr_hex.c ft_putnbr_rec.c \
			ft_putnbr_unsig.c ft_putnbr_uphex.c ft_putstr_2.c
SRC_GNL = get_next_line.c get_next_line_utils.c
SRC = $(SRC_LIBFT) $(SRC_PRINTF) $(SRC_GNL)
OBJ = $(SRC:.c=.o)
BIN_PATH = bin
BIN_OBJ = $(SRC:%.c=$(BIN_PATH)/%.o)

all: $(NAME)

$(NAME): $(OBJ)
	@mv -t $(BIN_PATH) $(OBJ)
	@$(AR) $(NAME) $(BIN_OBJ)
	@echo "libft.a created"

%.o: %.c
	@$(CC) $(CFLAGS) -c $<

clean:
	@$(RM) $(BIN_OBJ)
	@echo "libft objs removed"

fclean: clean
	@$(RM) $(NAME)
	@echo "libft.a removed"

re: fclean all

.PHONY: all clean fclean re
